# Generated by Django 6.0.2 on 2026-03-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youth',
            name='is_unemployed',
            field=models.BooleanField(default=False, verbose_name='Unemployed Youth'),
        ),
    ]
