"""
Django settings for lydo_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------ Debug helpers (crucial) ------------------
# Quick checklist to debug missing CSS/static templates:
# - Ensure `TEMPLATES['DIRS']` points to the frontend folder so
#   `{% load static %}` and `{% static 'style.css' %}` resolve correctly.
# - During local development `DEBUG = True` lets Django serve files
#   from the paths listed in `STATICFILES_DIRS` (set below).
# - If you open the HTML file directly (file://) the `{% %}` tags
#   are not processed — run the Django server and visit `/` instead.
# - To rule out caching, hard-refresh browser or add `?v=1` to CSS URL.
# ------------------------------------------------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tft%%3i$8q64@x(fjn!j!@39e&j7@nr5h#aj5a#i9m&4-uys53'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['youth-profiling-system.onrender.com']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Add this line
    'monitoring',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lydo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # THIS IS THE CRITICAL FIX:
        'DIRS': [os.path.join(BASE_DIR, '..', '..', 'frontend')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lydo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Priority:
# 1) `DATABASE_URL` env var (preferred)
# 2) Individual POSTGRES_* env vars
# 3) Fallback to local SQLite for development

def _parse_database_url(url: str):
    # Minimal DATABASE_URL parser (postgres://user:pass@host:port/dbname)
    result = urlparse(url)
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': result.path.lstrip('/'),
        'USER': result.username or 'postgres',
        'PASSWORD': result.password or '',
        'HOST': result.hostname or '127.0.0.1',
        'PORT': str(result.port or '5432'),
    }


# DATABASES placeholder and resolution order:
# - If `DATABASE_URL` is set prefer that (supports dj-database-url)
# - Else if any `POSTGRES_*` vars are set, use them
# - Else fall back to local defaults
# Example (keeps here as reference):
# DATABASES = {}
# if os.environ.get('DATABASE_URL'):
#     # prefer dj-database-url if installed, otherwise use local parser
#     try:
#         import dj_database_url
#
#         DATABASES['default'] = dj_database_url.parse(os.environ['DATABASE_URL'], conn_max_age=600)
#     except Exception:
#         DATABASES['default'] = _parse_database_url(os.environ['DATABASE_URL'])
#         DATABASES['default']['CONN_MAX_AGE'] = 600
#         DATABASES['default']['OPTIONS'] = {'connect_timeout': 10}
# elif os.environ.get('POSTGRES_DB') or os.environ.get('POSTGRES_USER') or os.environ.get('POSTGRES_PASSWORD') or os.environ.get('POSTGRES_HOST'):
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('POSTGRES_DB', 'lydo'),
#         'USER': os.environ.get('POSTGRES_USER', 'postgres'),
#         'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
#         # prefer IPv4 loopback to avoid IPv6 binding mismatch
#         'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
#         'PORT': os.environ.get('POSTGRES_PORT', '5432'),
#         'CONN_MAX_AGE': 600,
#         'OPTIONS': {'connect_timeout': 10},
#     }
# else:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lydo',
        'USER': 'postgres',
        'PASSWORD': '2022303023',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', '..', 'frontend'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True